# Generated by Django 2.2.4 on 2019-09-14 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hood', '0005_auto_20190914_1718'),
        ('users', '0003_auto_20190913_0624'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='hood.Location'),
        ),
    ]
