# Generated by Django 2.2.4 on 2019-09-14 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_profile_biz'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='biz',
        ),
    ]
