# Generated by Django 2.2.4 on 2019-09-13 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hood', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='business',
            old_name='hoodbizID',
            new_name='hood',
        ),
        migrations.RenameField(
            model_name='occupant',
            old_name='hoodID',
            new_name='hood',
        ),
        migrations.AlterField(
            model_name='business',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='hood.Location'),
        ),
        migrations.AlterField(
            model_name='neighbourhood',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='hood.Location'),
        ),
    ]
