# Generated by Django 2.2.4 on 2019-09-14 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hood', '0002_auto_20190913_0735'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='neighbourhood',
            name='location',
        ),
        migrations.AddField(
            model_name='neighbourhood',
            name='locations',
            field=models.ManyToManyField(to='hood.Location'),
        ),
        migrations.AlterField(
            model_name='business',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='hood.Location'),
        ),
    ]
