# Generated by Django 2.2.4 on 2019-09-14 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hood', '0003_auto_20190914_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
