# Generated by Django 2.2.4 on 2019-09-14 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hood', '0004_auto_20190914_1713'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='name',
            new_name='locationName',
        ),
        migrations.RenameField(
            model_name='neighbourhood',
            old_name='name',
            new_name='hoodname',
        ),
    ]
