# Generated by Django 2.2.4 on 2019-09-14 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hood', '0006_business_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='business',
            old_name='email',
            new_name='businessemail',
        ),
        migrations.RenameField(
            model_name='business',
            old_name='name',
            new_name='businessname',
        ),
    ]
